### ISSUE TITLE
Any plans to upgrade hydralit to support streamlit 1.4.0?

### ISSUE THREAD

**Issue by oggers** [TangleSpace/hydralit#19]
Hi guys, do you have plans to upgrade hydralit to support streamlit version 1.4.0?

**Comment by drtiwari** [comment]
Hi jackson, what an amazing job with Hydralit! Much appreciated and thanks for making this wonderful library. I second oggers and want to inquire the same question. Cheers

**Comment by drtiwari** [comment]
Hi Jackson, what an amazing job with Hydralit! Much appreciated and thanks for making this wonderful library. I second oggers and want to inquire the same question. Cheers

**Comment by TangleSpace** [comment]
Thanks for the support, it is very much appreciated. The short answer is I need to find out how exactly Streamlit has decided to change everything about the session state to see if I can repair the damage. I will have a look and push a release if I can, else the community deserves more than what Streamlit have been providing and I'm currently working on an extension to this project that will solve all these type of problems and more in one place.

FYI: I have now been in a running battle with the Streamlit people since mid last year as they don't like this package as it provides functionality that they want to charge everyone for in their business model, so they have been working towards breaking Hydralit for the last few releases.

Once again, thank you very much for your support, in the meantime, unless you are using absolute cutting edge features in Streamlit 1.4.0, I'd recommend you stay with version 1.3.1 to continue to use Hydralit. Please also feel free to provide suggestions on this project, as thousands of people are using it, but either it is amazing the way it is or no one provides me with suggestions for features, functions possibilities, which I doubt, so please let me know if you would like to see something or anything to make this more productive for you or the community.

**Comment by drtiwari** [comment]
I have already downgraded my streamlit to version 1.3.1 yesterday to keep on using Hydralit :)
I am sorry to hear your conflicts with streamlit, which i was partially aware of going through forums.
I wonder as they apparently want to monetize their work, sooner or later true open source flag-bearing will come against business interest. 
Is it possible you ask for their opinions and then later minor inclusions in your work (middle-ground)? 
As I wish getting featured at the top in community components will be a great boost and wider outreach to your voluminous work.
These are just polite suggestions as I really like your library and enthusiastically trying to integrate it in my MPV.
BTW is it amazing the way it is and from now onward I will definitely get back with suggestions and features request.
Thanks and cheers

**Comment by drtiwari** [comment]
I have already downgraded my streamlit to version 1.3.1 yesterday to keep on using Hydralit :)
I am sorry to hear your conflicts with streamlit, which i was partially aware of going through forums.
I wonder as they apparently want to monetize their work, sooner or later true open source flag-bearing will come against business interest.
Is it possible you ask for their opinions and then perform later minor inclusions in your work (middle-ground)?
As I think Hydralit getting featured at the top in community components will be a great boost and will provide wider outreach to your voluminous work.
These are just polite suggestions as I really like your library and enthusiastically trying to integrate it in my MPV.
BTW is it amazing the way it is and from now onward I will definitely get back with suggestions and features request.
Thanks and cheers

**Comment by oggers** [comment]
I also downgraded streamlit in order to keep using Hydralit. Tomorrow I will look at the differences they put into streamlit.

Very nice work you have done with Hydralit!!

**Comment by oggers** [comment]
Just created a [pull request](https://github.com/TangleSpace/hydralit/pull/20) that solves the problem with streamlit 1.4.0. Test it in your environment.

**Comment by TangleSpace** [comment]
A very big thank you for finding and correcting this issue. I have pushed a new release that allows for full support across all versions of Streamlit, including 1.4.0 with a fix derived from your solution, thank you very much for your support and hopefully you enjoy some of the other new features and fixes in this release.
