### ISSUE TITLE
how to link to another hydralit page?

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit#9]
Hi,

I want to do a hyperlink from some text on a subpage off Home to another hydralit page.  

 [Create metadata for your completed book](???) the page name being either the same or a shorter version like 'Create Metadata'

On the home page it's accomplished by a button - self.do_redirect('Tools') - what's the equivalent here?

**Comment by TangleSpace** [comment]
Not sure, if someone makes a new button component that looks like a link button, it would work the same as now, else Streamlit don't allow the style of their base widgets to be override, which is a pain.

Also the use of internal links has been changed to one shot use to a static (no widgets) app due to the Streamlit custom component execution model. All internal links when using the Hydralit navbar are not recommended, if internal links are required, it is recommended to disable the Hydralit navbar and return to the conventional Streamlit button menu (to change use_navbar=False in the Hydralit constructor). You can still have an internal link, it will redirect to the target app, but if you trigger a rerun from that app (changing the value of a widget for example), it will bounce back to the calling app. I struggled for over a week to get around it, but once again Streamlit have not provided a way to halt the rerun function in a custom widget, so the result is if i left it as previous, it would load the target app twice to make sure the navbar state matched where the redirect link too you.
